image: "ruby:2.6.6"

before_script:
 # - apt-get update -qq && apt-get install -y -qq sqlite3 libsqlite3-dev nodejs
#  - ruby -v
 # - which ruby
 # - gem install bundler --no-document
 # - gem install rails
 # - gem install sqlite3
 # - bundle install --jobs $(nproc) "${FLAGS[@]}"

test:
  script:
    - Write-Output "Hello World"
