image: "ruby:2.6.6"

before_script:
  - Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
  - ruby -v
  - choco install nodejs --yes
  - choco install yarn --yes
  - gem update --system
  - bundle install
  - bundle update

test:
  script:
    - bundle exec rake db:migrate RAILS_ENV=test
    - bundle exec rspec
